export { default as SearchBox } from "./SearchBox/index";
export { default as Slider } from "./Slider/index";
export { default as Category } from "./Category/index";
export {default as Story} from "./Story/index";
export {default as ShowSwiper} from "./ShowSwiper/index";
export {default as HomeFeatures} from "./HomeFeatures/index";
export {default as MainCategory} from "./MainCategory/index";
export {default as Suggestion} from "./Suggestion/index";
export {default as PopularBrands} from "./PopularBrands/index";
export {default as DigitalGoods} from "./DigitalGoods/index";
export {default as BestSelling} from "./BestSelling/index";
export {default as SelectionDiscount} from "./SelectionDiscount/index";
export {default as CountDownTimer} from "./CountDownTimer/index";
export {default as Blog} from "./Blog/index";
export {default as SuperMarket} from "./SuperMarket/index";
export {default as SearchFilter} from "./SearchFilter/index";
export {default as CheckBox} from "./CheckBox/index";
export {default as PhoneCard} from "./PhoneCard/index";
export {default as ShowPhoneCards} from "./ShowPhoneCards/index";
export {default as ShowPindo} from "./ShowPindo/index";
export {default as StarRating} from "./StarRating/index";
export {default as ProgresBar} from "./ProgresBar/index";
export {default as ProductIconsList} from "./ProductIconsList/index";
export {default as ProductPhotos} from "./ProductPhotos/index";
export {default as ProductColors} from "./ProductColors/index";
export {default as ProductInsurance} from "./ProductInsurance/index";
export {default as ProductFeatures} from "./ProductFeatures/index";
export {default as ProductAnotherSellers} from "./ProductAnotherSellers/index";
export {default as ProductRelatedVideos} from "./ProductRelatedVideos/index";
export {default as ProductDetailsCategory} from "./ProductDetailsCategory/index";
export {default as ProductIntroduction} from "./ProductIntroduction/index";
export {default as ProductSpecifications} from "./ProductSpecifications/index";
export {default as ProductUsersScoresAndOpinions} from "./ProductUsersScoresAndOpinions/index";
export {default as ProductUsersQuestions} from "./ProductUsersQuestions/index";
export {default as DigikalaBuyingBenefits} from "./DigikalaBuyingBenefits/index";
export {default as QuestionCard} from "./QuestionCard/index";